/**
 * Conjunto Unicode padrão, agrupado como no seletor do Discord.
 *
 * É um recorte curado, não a tabela Unicode inteira: carregar as ~3800
 * sequências custaria mais de um megabyte de bundle para um app que roda
 * offline, e a cauda longa quase nunca é usada. As palavras-chave estão em
 * português porque a busca é feita em português.
 */
export interface EmojiEntry {
  /** O caractere em si. */
  char: string;
  /** Nome curto, usado como `:atalho:` e no rodapé do seletor. */
  name: string;
  /** Termos de busca, separados por espaço. */
  keywords: string;
}

export interface EmojiCategory {
  id: string;
  label: string;
  icon: string;
  emojis: EmojiEntry[];
}

const entry = (char: string, name: string, keywords = ""): EmojiEntry => ({
  char,
  name,
  keywords: `${name} ${keywords}`.trim(),
});

export const EMOJI_CATEGORIES: EmojiCategory[] = [
  {
    id: "pessoas",
    label: "Rostos e pessoas",
    icon: "😀",
    emojis: [
      entry("😀", "sorriso", "feliz alegre rosto"),
      entry("😃", "sorrisão", "feliz alegre rosto"),
      entry("😄", "sorriso aberto", "feliz alegre"),
      entry("😁", "sorriso radiante", "feliz dentes"),
      entry("😆", "gargalhada", "rindo feliz"),
      entry("😅", "riso nervoso", "suor alívio"),
      entry("🤣", "rolando de rir", "rindo muito engraçado"),
      entry("😂", "chorando de rir", "lágrima engraçado"),
      entry("🙂", "sorriso leve", "ok tranquilo"),
      entry("🙃", "de cabeça para baixo", "ironia sarcasmo"),
      entry("😉", "piscadinha", "flerte"),
      entry("😊", "sorriso tímido", "feliz corado"),
      entry("😇", "anjo", "auréola inocente"),
      entry("🥰", "apaixonado", "corações amor"),
      entry("😍", "olhos de coração", "amor paixão"),
      entry("🤩", "estrelas nos olhos", "uau incrível"),
      entry("😘", "beijo", "amor carinho"),
      entry("😗", "beijinho", "carinho"),
      entry("😚", "beijo fechado", "carinho"),
      entry("🥲", "sorriso com lágrima", "emocionado"),
      entry("😋", "delícia", "gostoso língua"),
      entry("😛", "língua de fora", "brincadeira"),
      entry("😜", "língua e piscadinha", "brincadeira zoeira"),
      entry("🤪", "maluco", "doido zoeira"),
      entry("😝", "língua olhos fechados", "zoeira"),
      entry("🤑", "cifrão", "dinheiro rico"),
      entry("🤗", "abraço", "carinho acolhimento"),
      entry("🤭", "risinho", "opa vergonha"),
      entry("🤫", "silêncio", "shh segredo"),
      entry("🤔", "pensando", "dúvida hmm"),
      entry("🤐", "boca fechada", "segredo"),
      entry("🤨", "sobrancelha erguida", "desconfiado duvidoso"),
      entry("😐", "neutro", "sem reação"),
      entry("😑", "sem expressão", "tédio"),
      entry("😶", "sem boca", "mudo"),
      entry("😏", "sorrisinho", "malicioso"),
      entry("😒", "de lado", "desanimado chato"),
      entry("🙄", "revirando os olhos", "tédio irritado"),
      entry("😬", "constrangido", "careta desconforto"),
      entry("😮‍💨", "suspiro", "alívio cansaço"),
      entry("🤥", "mentiroso", "pinóquio nariz"),
      entry("😌", "aliviado", "calmo"),
      entry("😔", "cabisbaixo", "triste"),
      entry("😪", "sono", "cansado"),
      entry("🤤", "babando", "desejo"),
      entry("😴", "dormindo", "sono zzz"),
      entry("😷", "máscara", "doente"),
      entry("🤒", "febre", "termômetro doente"),
      entry("🤕", "machucado", "curativo"),
      entry("🤢", "enjoado", "nojo"),
      entry("🤮", "vomitando", "nojo passando mal"),
      entry("🤧", "espirro", "gripe resfriado"),
      entry("🥵", "calor", "quente derretendo"),
      entry("🥶", "frio", "congelando"),
      entry("😵", "tonto", "atordoado"),
      entry("😵‍💫", "confuso", "tonto"),
      entry("🤯", "cabeça explodindo", "chocado uau"),
      entry("🤠", "chapéu de caubói", "country"),
      entry("🥳", "festa", "comemoração aniversário"),
      entry("😎", "óculos escuros", "estiloso legal"),
      entry("🤓", "nerd", "estudioso óculos"),
      entry("🧐", "monóculo", "investigando"),
      entry("😕", "confuso", "dúvida"),
      entry("😟", "preocupado", "aflito"),
      entry("🙁", "triste leve", "chateado"),
      entry("😯", "surpreso", "opa"),
      entry("😲", "chocado", "espanto"),
      entry("😳", "corado", "vergonha surpresa"),
      entry("🥺", "olhinhos", "pidão fofo carente"),
      entry("😦", "assustado", "boca aberta"),
      entry("😧", "angustiado", "aflito"),
      entry("😨", "com medo", "assustado"),
      entry("😰", "ansioso", "suor medo"),
      entry("😥", "decepcionado", "aliviado triste"),
      entry("😢", "chorando", "triste lágrima"),
      entry("😭", "chorando muito", "triste desespero"),
      entry("😱", "gritando de medo", "pavor"),
      entry("😖", "sofrendo", "incomodado"),
      entry("😣", "perseverando", "esforço"),
      entry("😞", "desapontado", "triste"),
      entry("😓", "suando frio", "derrota"),
      entry("😩", "exausto", "cansado"),
      entry("😫", "cansadíssimo", "esgotado"),
      entry("🥱", "bocejo", "sono tédio"),
      entry("😤", "bufando", "irritado determinado"),
      entry("😡", "bravo", "raiva vermelho"),
      entry("😠", "irritado", "raiva"),
      entry("🤬", "xingando", "raiva palavrão"),
      entry("😈", "diabinho", "travesso"),
      entry("💀", "caveira", "morto morri"),
      entry("💩", "cocô", "bosta"),
      entry("🤡", "palhaço", "piada"),
      entry("👻", "fantasma", "assombração"),
      entry("👽", "alienígena", "et"),
      entry("🤖", "robô", "bot"),
      entry("👋", "tchau", "oi acenando mão"),
      entry("🤚", "mão levantada", "parar"),
      entry("✋", "mão aberta", "parar cinco"),
      entry("👌", "ok", "joia perfeito"),
      entry("🤌", "dedos juntos", "itália"),
      entry("🤏", "pouquinho", "pequeno"),
      entry("✌️", "paz", "vitória dois"),
      entry("🤞", "dedos cruzados", "sorte torcendo"),
      entry("🤟", "amo você", "rock"),
      entry("🤘", "rock", "chifrinho metal"),
      entry("🤙", "me liga", "shaka"),
      entry("👈", "aponta esquerda", "seta"),
      entry("👉", "aponta direita", "seta"),
      entry("👆", "aponta cima", "seta"),
      entry("👇", "aponta baixo", "seta"),
      entry("☝️", "indicador", "um atenção"),
      entry("👍", "joia", "curti positivo like"),
      entry("👎", "descurti", "negativo dislike"),
      entry("✊", "punho", "força luta"),
      entry("👊", "soco", "toca aqui"),
      entry("👏", "palmas", "aplauso parabéns"),
      entry("🙌", "mãos ao alto", "comemorando"),
      entry("🤝", "aperto de mão", "acordo"),
      entry("🙏", "por favor", "obrigado reza"),
      entry("💪", "força", "bíceps músculo"),
      entry("🧠", "cérebro", "mente"),
      entry("👀", "olhos", "olhando spy"),
      entry("👶", "bebê", "criança"),
      entry("🧑", "pessoa", "gente"),
      entry("👨", "homem", "cara"),
      entry("👩", "mulher", "moça"),
      entry("🧔", "barba", "pessoa"),
      entry("👮", "policial", "polícia"),
      entry("👷", "operário", "obra construção"),
      entry("🕵️", "detetive", "investigador"),
      entry("👨‍💻", "programador", "dev tecnologia"),
      entry("👩‍💻", "programadora", "dev tecnologia"),
      entry("🦸", "super-herói", "herói"),
      entry("🦹", "vilão", "supervilão"),
      entry("🎅", "papai noel", "natal"),
      entry("🧙", "mago", "feiticeiro"),
      entry("🧟", "zumbi", "morto-vivo"),
      entry("💃", "dançando", "dança festa"),
      entry("🕺", "dançarino", "dança festa"),
      entry("🤦", "facepalm", "descrença mão na cara"),
      entry("🤷", "sei lá", "ombros dúvida"),
      entry("🧘", "meditando", "calma yoga"),
    ],
  },
  {
    id: "natureza",
    label: "Natureza",
    icon: "🐶",
    emojis: [
      entry("🐶", "cachorro", "dog cão"),
      entry("🐱", "gato", "cat"),
      entry("🐭", "rato", "camundongo"),
      entry("🐹", "hamster", "roedor"),
      entry("🐰", "coelho", "páscoa"),
      entry("🦊", "raposa", "fox"),
      entry("🐻", "urso", "bear"),
      entry("🐼", "panda", "urso"),
      entry("🐨", "coala", "austrália"),
      entry("🐯", "tigre", "felino"),
      entry("🦁", "leão", "felino"),
      entry("🐮", "vaca", "boi"),
      entry("🐷", "porco", "suíno"),
      entry("🐸", "sapo", "rã"),
      entry("🐵", "macaco", "primata"),
      entry("🙈", "não vejo", "macaco"),
      entry("🙉", "não ouço", "macaco"),
      entry("🙊", "não falo", "macaco"),
      entry("🐔", "galinha", "ave"),
      entry("🐧", "pinguim", "gelo"),
      entry("🐦", "pássaro", "ave"),
      entry("🦅", "águia", "ave"),
      entry("🦆", "pato", "ave"),
      entry("🦉", "coruja", "ave noite"),
      entry("🐺", "lobo", "wolf"),
      entry("🐗", "javali", "porco"),
      entry("🐴", "cavalo", "égua"),
      entry("🦄", "unicórnio", "fantasia"),
      entry("🐝", "abelha", "mel"),
      entry("🐛", "lagarta", "inseto"),
      entry("🦋", "borboleta", "inseto"),
      entry("🐌", "caracol", "lesma devagar"),
      entry("🐞", "joaninha", "inseto"),
      entry("🕷️", "aranha", "inseto"),
      entry("🐢", "tartaruga", "devagar"),
      entry("🐍", "cobra", "serpente"),
      entry("🦎", "lagarto", "réptil"),
      entry("🦖", "dinossauro", "trex"),
      entry("🐙", "polvo", "mar"),
      entry("🦑", "lula", "mar"),
      entry("🦐", "camarão", "mar"),
      entry("🦀", "caranguejo", "mar"),
      entry("🐡", "baiacu", "peixe"),
      entry("🐠", "peixe tropical", "mar"),
      entry("🐟", "peixe", "mar"),
      entry("🐬", "golfinho", "mar"),
      entry("🐳", "baleia", "mar"),
      entry("🦈", "tubarão", "mar"),
      entry("🐊", "crocodilo", "jacaré"),
      entry("🐘", "elefante", "grande"),
      entry("🦒", "girafa", "pescoço"),
      entry("🦓", "zebra", "listras"),
      entry("🐄", "vaca leiteira", "gado"),
      entry("🐑", "ovelha", "lã"),
      entry("🐐", "cabra", "bode"),
      entry("🌵", "cacto", "deserto"),
      entry("🌲", "pinheiro", "árvore"),
      entry("🌳", "árvore", "floresta"),
      entry("🌴", "coqueiro", "praia"),
      entry("🌱", "broto", "planta"),
      entry("🌿", "erva", "folha"),
      entry("☘️", "trevo", "sorte"),
      entry("🍀", "trevo de quatro folhas", "sorte"),
      entry("🍁", "folha de bordo", "outono"),
      entry("🍂", "folhas caídas", "outono"),
      entry("🌸", "flor de cerejeira", "primavera"),
      entry("🌺", "hibisco", "flor"),
      entry("🌻", "girassol", "flor"),
      entry("🌹", "rosa", "flor amor"),
      entry("🌷", "tulipa", "flor"),
      entry("🌍", "planeta", "terra mundo"),
      entry("🌙", "lua", "noite"),
      entry("⭐", "estrela", "favorito"),
      entry("🌟", "estrela brilhante", "destaque"),
      entry("✨", "brilhos", "magia novo"),
      entry("⚡", "raio", "energia rápido"),
      entry("🔥", "fogo", "quente top"),
      entry("💧", "gota", "água"),
      entry("🌊", "onda", "mar praia"),
      entry("☀️", "sol", "dia calor"),
      entry("⛅", "sol entre nuvens", "tempo"),
      entry("☁️", "nuvem", "tempo"),
      entry("🌧️", "chuva", "tempo"),
      entry("❄️", "floco de neve", "frio"),
      entry("🌈", "arco-íris", "cores"),
    ],
  },
  {
    id: "comida",
    label: "Comida e bebida",
    icon: "🍔",
    emojis: [
      entry("🍏", "maçã verde", "fruta"),
      entry("🍎", "maçã", "fruta"),
      entry("🍐", "pera", "fruta"),
      entry("🍊", "laranja", "fruta"),
      entry("🍋", "limão", "fruta"),
      entry("🍌", "banana", "fruta"),
      entry("🍉", "melancia", "fruta"),
      entry("🍇", "uva", "fruta"),
      entry("🍓", "morango", "fruta"),
      entry("🫐", "mirtilo", "fruta"),
      entry("🍒", "cereja", "fruta"),
      entry("🍑", "pêssego", "fruta"),
      entry("🥭", "manga", "fruta"),
      entry("🍍", "abacaxi", "fruta"),
      entry("🥥", "coco", "fruta"),
      entry("🥑", "abacate", "fruta"),
      entry("🍅", "tomate", "legume"),
      entry("🌽", "milho", "espiga"),
      entry("🥕", "cenoura", "legume"),
      entry("🥔", "batata", "legume"),
      entry("🍞", "pão", "padaria"),
      entry("🥐", "croissant", "padaria"),
      entry("🧀", "queijo", "laticínio"),
      entry("🥚", "ovo", "café da manhã"),
      entry("🍳", "ovo frito", "café da manhã"),
      entry("🥓", "bacon", "carne"),
      entry("🍔", "hambúrguer", "lanche"),
      entry("🍟", "batata frita", "lanche"),
      entry("🌭", "cachorro-quente", "lanche"),
      entry("🍕", "pizza", "lanche"),
      entry("🌮", "taco", "mexicano"),
      entry("🌯", "burrito", "mexicano"),
      entry("🥗", "salada", "saudável"),
      entry("🍝", "macarrão", "massa"),
      entry("🍜", "lámen", "sopa"),
      entry("🍣", "sushi", "japonês"),
      entry("🍤", "camarão frito", "japonês"),
      entry("🍚", "arroz", "prato"),
      entry("🍛", "curry", "prato"),
      entry("🥩", "carne", "churrasco"),
      entry("🍗", "coxa de frango", "carne"),
      entry("🍿", "pipoca", "cinema"),
      entry("🧂", "sal", "tempero"),
      entry("🍦", "sorvete", "sobremesa"),
      entry("🍩", "rosquinha", "donut"),
      entry("🍪", "biscoito", "cookie"),
      entry("🎂", "bolo de aniversário", "festa"),
      entry("🍰", "fatia de bolo", "sobremesa"),
      entry("🧁", "cupcake", "sobremesa"),
      entry("🍫", "chocolate", "doce"),
      entry("🍬", "bala", "doce"),
      entry("🍯", "mel", "doce"),
      entry("☕", "café", "bebida quente"),
      entry("🍵", "chá", "bebida quente"),
      entry("🧃", "suco", "bebida"),
      entry("🥤", "refrigerante", "bebida copo"),
      entry("🍺", "cerveja", "bebida chopp"),
      entry("🍻", "brinde", "cerveja comemoração"),
      entry("🍷", "vinho", "bebida taça"),
      entry("🥂", "taças", "brinde comemoração"),
      entry("🍸", "coquetel", "drink"),
      entry("🥃", "uísque", "destilado"),
      entry("🧉", "chimarrão", "mate"),
    ],
  },
  {
    id: "atividades",
    label: "Atividades",
    icon: "⚽",
    emojis: [
      entry("⚽", "futebol", "bola esporte"),
      entry("🏀", "basquete", "bola esporte"),
      entry("🏈", "futebol americano", "esporte"),
      entry("⚾", "beisebol", "esporte"),
      entry("🎾", "tênis", "esporte"),
      entry("🏐", "vôlei", "esporte"),
      entry("🏉", "rugby", "esporte"),
      entry("🎱", "sinuca", "bilhar"),
      entry("🏓", "tênis de mesa", "pingue-pongue"),
      entry("🏸", "badminton", "esporte"),
      entry("🥅", "gol", "trave"),
      entry("🏒", "hóquei", "esporte"),
      entry("🥊", "boxe", "luva luta"),
      entry("🥋", "artes marciais", "judô karatê"),
      entry("⛳", "golfe", "esporte"),
      entry("🎣", "pescaria", "pesca"),
      entry("🏊", "natação", "nadar"),
      entry("🏄", "surfe", "onda"),
      entry("🚴", "ciclismo", "bicicleta"),
      entry("🏋️", "musculação", "academia peso"),
      entry("🤸", "ginástica", "acrobacia"),
      entry("⛷️", "esqui", "neve"),
      entry("🏆", "troféu", "vitória campeão"),
      entry("🥇", "medalha de ouro", "primeiro"),
      entry("🥈", "medalha de prata", "segundo"),
      entry("🥉", "medalha de bronze", "terceiro"),
      entry("🎮", "videogame", "controle jogo"),
      entry("🕹️", "joystick", "arcade jogo"),
      entry("🎲", "dado", "sorte jogo"),
      entry("♟️", "xadrez", "peão jogo"),
      entry("🎯", "alvo", "acerto dardo"),
      entry("🎰", "caça-níquel", "cassino"),
      entry("🎳", "boliche", "esporte"),
      entry("🎨", "pintura", "arte paleta"),
      entry("🎬", "claquete", "cinema filme"),
      entry("🎤", "microfone", "cantar karaokê"),
      entry("🎧", "fone de ouvido", "música"),
      entry("🎵", "nota musical", "música"),
      entry("🎶", "notas musicais", "música"),
      entry("🎸", "guitarra", "música"),
      entry("🥁", "bateria", "música tambor"),
      entry("🎹", "teclado", "piano música"),
      entry("🎺", "trompete", "música"),
      entry("🎪", "circo", "tenda"),
      entry("🎉", "festa", "comemoração confete"),
      entry("🎊", "confete", "festa"),
      entry("🎈", "balão", "festa aniversário"),
      entry("🎁", "presente", "aniversário natal"),
      entry("🎃", "abóbora", "halloween"),
      entry("🎄", "árvore de natal", "natal"),
    ],
  },
  {
    id: "viagem",
    label: "Viagem e lugares",
    icon: "🚗",
    emojis: [
      entry("🚗", "carro", "automóvel"),
      entry("🚕", "táxi", "carro"),
      entry("🚙", "suv", "carro"),
      entry("🚌", "ônibus", "transporte"),
      entry("🚑", "ambulância", "emergência"),
      entry("🚓", "viatura", "polícia"),
      entry("🚒", "caminhão de bombeiro", "emergência"),
      entry("🚚", "caminhão", "carga"),
      entry("🚜", "trator", "fazenda"),
      entry("🏍️", "moto", "motocicleta"),
      entry("🚲", "bicicleta", "bike"),
      entry("🛴", "patinete", "scooter"),
      entry("🚂", "trem", "locomotiva"),
      entry("🚄", "trem-bala", "trem"),
      entry("🚇", "metrô", "transporte"),
      entry("✈️", "avião", "voo viagem"),
      entry("🚀", "foguete", "espaço lançamento"),
      entry("🛸", "disco voador", "óvni"),
      entry("🚁", "helicóptero", "voo"),
      entry("⛵", "veleiro", "barco"),
      entry("🚢", "navio", "barco"),
      entry("⚓", "âncora", "barco"),
      entry("⛽", "posto", "gasolina"),
      entry("🚦", "semáforo", "trânsito"),
      entry("🗺️", "mapa", "viagem"),
      entry("🏔️", "montanha", "neve"),
      entry("🌋", "vulcão", "erupção"),
      entry("🏕️", "acampamento", "barraca"),
      entry("🏖️", "praia", "guarda-sol férias"),
      entry("🏝️", "ilha", "praia"),
      entry("🏜️", "deserto", "cacto"),
      entry("🏠", "casa", "lar"),
      entry("🏡", "casa com jardim", "lar"),
      entry("🏢", "prédio", "escritório"),
      entry("🏥", "hospital", "saúde"),
      entry("🏦", "banco", "dinheiro"),
      entry("🏫", "escola", "estudo"),
      entry("🏭", "fábrica", "indústria"),
      entry("🏰", "castelo", "medieval"),
      entry("🗿", "moai", "estátua"),
      entry("🗽", "estátua da liberdade", "nova york"),
      entry("🌆", "cidade", "entardecer"),
      entry("🌃", "cidade à noite", "noite"),
      entry("🌉", "ponte", "noite"),
      entry("🎡", "roda-gigante", "parque"),
      entry("🎢", "montanha-russa", "parque"),
    ],
  },
  {
    id: "objetos",
    label: "Objetos",
    icon: "💡",
    emojis: [
      entry("⌚", "relógio de pulso", "hora"),
      entry("📱", "celular", "telefone"),
      entry("💻", "notebook", "computador laptop"),
      entry("🖥️", "computador", "desktop"),
      entry("🖨️", "impressora", "papel"),
      entry("⌨️", "teclado", "digitar"),
      entry("🖱️", "mouse", "computador"),
      entry("💾", "disquete", "salvar"),
      entry("💿", "cd", "disco"),
      entry("📷", "câmera", "foto"),
      entry("📹", "filmadora", "vídeo"),
      entry("🎥", "câmera de cinema", "filme"),
      entry("📺", "televisão", "tv"),
      entry("📻", "rádio", "som"),
      entry("🔋", "bateria", "energia"),
      entry("🔌", "tomada", "energia"),
      entry("💡", "lâmpada", "ideia"),
      entry("🔦", "lanterna", "luz"),
      entry("🕯️", "vela", "luz"),
      entry("🧯", "extintor", "fogo segurança"),
      entry("🔧", "chave inglesa", "ferramenta conserto"),
      entry("🔨", "martelo", "ferramenta"),
      entry("🪛", "chave de fenda", "ferramenta"),
      entry("⚙️", "engrenagem", "configuração"),
      entry("🔒", "cadeado fechado", "seguro privado"),
      entry("🔓", "cadeado aberto", "destravado"),
      entry("🔑", "chave", "acesso"),
      entry("🗝️", "chave antiga", "acesso"),
      entry("🚪", "porta", "entrada"),
      entry("🛏️", "cama", "dormir"),
      entry("🚿", "chuveiro", "banho"),
      entry("🧹", "vassoura", "limpeza"),
      entry("🧺", "cesto", "roupa"),
      entry("🛒", "carrinho", "compras"),
      entry("💰", "saco de dinheiro", "grana"),
      entry("💵", "dinheiro", "nota"),
      entry("💳", "cartão", "pagamento"),
      entry("🧾", "recibo", "nota fiscal"),
      entry("✉️", "envelope", "email carta"),
      entry("📦", "caixa", "pacote entrega"),
      entry("📅", "calendário", "data"),
      entry("📈", "gráfico em alta", "crescimento"),
      entry("📉", "gráfico em baixa", "queda"),
      entry("📊", "gráfico de barras", "dados"),
      entry("📋", "prancheta", "lista"),
      entry("📌", "alfinete", "fixar"),
      entry("📎", "clipe", "anexo"),
      entry("✂️", "tesoura", "cortar"),
      entry("📝", "anotação", "escrever nota"),
      entry("📖", "livro aberto", "leitura"),
      entry("📚", "livros", "estudo"),
      entry("🔍", "lupa", "buscar pesquisar"),
      entry("🔔", "sino", "notificação"),
      entry("🔕", "sino cortado", "silenciar"),
      entry("📢", "megafone", "aviso"),
      entry("🧪", "tubo de ensaio", "laboratório teste"),
      entry("💊", "remédio", "pílula"),
      entry("🩹", "curativo", "machucado"),
      entry("🛡️", "escudo", "proteção"),
      entry("⚔️", "espadas", "batalha"),
      entry("🧲", "ímã", "atração"),
      entry("🧭", "bússola", "direção"),
      entry("⏰", "despertador", "alarme"),
      entry("⏳", "ampulheta", "tempo espera"),
    ],
  },
  {
    id: "simbolos",
    label: "Símbolos",
    icon: "❤️",
    emojis: [
      entry("❤️", "coração vermelho", "amor"),
      entry("🧡", "coração laranja", "amor"),
      entry("💛", "coração amarelo", "amor"),
      entry("💚", "coração verde", "amor"),
      entry("💙", "coração azul", "amor"),
      entry("💜", "coração roxo", "amor"),
      entry("🖤", "coração preto", "amor"),
      entry("🤍", "coração branco", "amor"),
      entry("💔", "coração partido", "término tristeza"),
      entry("💕", "dois corações", "amor"),
      entry("💖", "coração brilhante", "amor"),
      entry("💯", "cem", "nota máxima top"),
      entry("💢", "irritação", "raiva"),
      entry("💬", "balão de fala", "conversa"),
      entry("💭", "balão de pensamento", "pensar"),
      entry("🗯️", "balão de raiva", "grito"),
      entry("✅", "check verde", "feito ok"),
      entry("☑️", "caixa marcada", "feito"),
      entry("✔️", "check", "feito"),
      entry("❌", "xis", "errado não"),
      entry("❎", "xis verde", "não"),
      entry("➕", "mais", "somar"),
      entry("➖", "menos", "subtrair"),
      entry("➗", "divisão", "dividir"),
      entry("❓", "interrogação", "dúvida"),
      entry("❗", "exclamação", "atenção"),
      entry("⚠️", "atenção", "cuidado alerta"),
      entry("🚫", "proibido", "bloqueado"),
      entry("♻️", "reciclagem", "sustentável"),
      entry("🔄", "atualizar", "recarregar sincronizar"),
      entry("🔗", "link", "corrente"),
      entry("➡️", "seta direita", "próximo"),
      entry("⬅️", "seta esquerda", "voltar"),
      entry("⬆️", "seta cima", "subir"),
      entry("⬇️", "seta baixo", "descer"),
      entry("🔺", "triângulo vermelho", "alta"),
      entry("🔻", "triângulo invertido", "baixa"),
      entry("⏸️", "pausar", "pausa"),
      entry("▶️", "reproduzir", "play"),
      entry("⏹️", "parar", "stop"),
      entry("⏭️", "próxima", "pular"),
      entry("🔊", "som alto", "volume"),
      entry("🔇", "mudo", "sem som"),
      entry("🔞", "dezoito", "adulto"),
      entry("♾️", "infinito", "sem fim"),
      entry("🆗", "ok", "certo"),
      entry("🆕", "novo", "new"),
      entry("🔥", "em alta", "fogo trending"),
      entry("⭕", "círculo", "certo"),
      entry("🟢", "bola verde", "online disponível"),
      entry("🟡", "bola amarela", "ausente"),
      entry("🔴", "bola vermelha", "ocupado gravando"),
      entry("⚫", "bola preta", "offline"),
      entry("🔶", "losango laranja", "destaque"),
      entry("💠", "losango azul", "destaque"),
    ],
  },
  {
    id: "bandeiras",
    label: "Bandeiras",
    icon: "🏳️",
    emojis: [
      entry("🏳️", "bandeira branca", "rendição"),
      entry("🏴", "bandeira preta", "pirata"),
      entry("🏁", "bandeira quadriculada", "chegada corrida"),
      entry("🚩", "bandeira vermelha", "alerta"),
      entry("🏳️‍🌈", "bandeira do arco-íris", "orgulho lgbt"),
      entry("🇧🇷", "brasil", "bandeira brasileira"),
      entry("🇵🇹", "portugal", "bandeira"),
      entry("🇺🇸", "estados unidos", "bandeira eua"),
      entry("🇦🇷", "argentina", "bandeira"),
      entry("🇯🇵", "japão", "bandeira"),
      entry("🇩🇪", "alemanha", "bandeira"),
      entry("🇫🇷", "frança", "bandeira"),
      entry("🇮🇹", "itália", "bandeira"),
      entry("🇪🇸", "espanha", "bandeira"),
      entry("🇬🇧", "reino unido", "bandeira"),
      entry("🇨🇦", "canadá", "bandeira"),
      entry("🇲🇽", "méxico", "bandeira"),
      entry("🇰🇷", "coreia do sul", "bandeira"),
      entry("🇨🇳", "china", "bandeira"),
      entry("🇮🇳", "índia", "bandeira"),
    ],
  },
];

export const ALL_EMOJI: EmojiEntry[] = EMOJI_CATEGORIES.flatMap(
  (category) => category.emojis,
);

/** Remove acento para a busca casar "coracao" com "coração". */
const fold = (value: string) =>
  value
    .toLowerCase()
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "");

export function searchEmoji(query: string, limit = 90) {
  const needle = fold(query.trim());
  if (!needle) return [];
  const starts: EmojiEntry[] = [];
  const contains: EmojiEntry[] = [];
  // Um mesmo caractere pode estar em duas categorias (🔥 é natureza e é
  // símbolo). Na busca ele precisa aparecer uma vez só.
  const seen = new Set<string>();
  for (const item of ALL_EMOJI) {
    if (seen.has(item.char)) continue;
    const haystack = fold(item.keywords);
    if (haystack.startsWith(needle) || fold(item.name).startsWith(needle)) {
      starts.push(item);
      seen.add(item.char);
    } else if (haystack.includes(needle)) {
      contains.push(item);
      seen.add(item.char);
    }
    if (starts.length >= limit) break;
  }
  return [...starts, ...contains].slice(0, limit);
}
